/public/
    index.html
    success.html
    styles.css
    logo.png
/functions/
    sendConfirmation.js
netlify.toml

[context.production.environment]
  # Set these in Netlify site settings (Site settings → Build & deploy → Environment)
  # SENDGRID_API_KEY = "..." 
  # SENDER_EMAIL = "noreply@tedxduth.gr"
  # ORGANIZER_EMAIL = "g.dalakouras@tedxduth.gr"
